Repository InstituteforDiseaseModeling/covasim, pull requests merged in 2020-04, with the labels that each got.

#93 COVASim UI MVP
  covasim/webapp/cova_app.css
  covasim/webapp/cova_app.js
  covasim/webapp/cova_app.py
  covasim/webapp/index.html
Labels: CovasimUI

#101 Add panel resizing
  covasim/webapp/cova_app.css
  covasim/webapp/cova_app.js
  covasim/webapp/index.html
Labels: CovasimUI

#155 Docs redirect
  docs/index.html
  docs/variables.txt
Labels: documentation

#122 Add get_country_household_sizes to data.loaders.
  covasim/data/loaders.py
  tests/test_country_households.py
  tests/unittests/test_data_loaders.py
  tests/unittests/un_household_size_sample.xlsx
Labels: doing

#189 Update NOTICE file
  covasim/webapp/npm-shrinkwrap.json
  covasim/webapp/package.json
  licenses/.npmrc
  licenses/NOTICE
  licenses/custom/coronadatascraper-data/package.json
  licenses/custom/covid-tracking-data/LICENSE
  licenses/custom/covid-tracking-data/package.json
  licenses/custom/google-fonts/open-sans/LICENSE
  licenses/custom/google-fonts/open-sans/package.json
  licenses/custom/license-format.json
  licenses/custom/polyfill.io/LICENSE
  licenses/custom/polyfill.io/package.json
  licenses/custom/polyfill/package.json
  licenses/custom/roboto-font/package.json
  licenses/custom/themify-icons/package.json
  licenses/notice.js
  licenses/notice.py
  licenses/package.json
Labels: documentation, legal
